<?php  $uqtab = rand().time();?>
<div class="inner-<?php echo $uqtab ?>">
<?php
$options  = $this->getConfigObject();
$maxtitle = $options->item_title_max_characs;
$post     = Mage::app()->getRequest()->getPost();
$type     =  (!empty($post['pdt_type']))?$post['pdt_type']:$options->list_products_by;

if( $type!='' ){
	if( $type == 'order' ){
        $first_ob = explode(',', $options->order_type);
        $orderby = (!empty($post['orderby']))?$post['orderby']:$first_ob[0];
		$child_items = $this->getProductsOrder($orderby);
        $total = $this->getProductsOrder($orderby, 1);
	} else {
        $first_ob = explode(',', $options->product_category);
        $catid   = (!empty($post['catid']))?$post['catid']:$first_ob[0]; //die($catid);
		$child_items = $this->getProductsCat($catid);
        $total =  $this->getProductsCat($catid, 1);
	}
}
if( !empty($child_items) ) {
	if( $type!='' ){
		$k = $post['numberstart'];
	} else {
		$k = 0;
	}
foreach( $child_items  as $item ){ $k++;
$_product = Mage::getModel('catalog/product')->load($item->id);
$class_first ='';
$class_first .= (($k-1)%(int)$options->devices_wide == 0)?' wide-first':'';
$class_first .= (($k-1)%(int)$options->devices_normal == 0)?' normal-first':'';
$class_first .= (($k-1)%(int)$options->devices_tabletlandscape == 0)?' tabletlandscape-first':'';
$class_first .= (($k-1)%(int)$options->devices_tabletportrait == 0)?' tabletportrait-first':'';
$class_first .= (($k-1)%(int)$options->devices_mobilelandscape == 0)?' mobilelandscape-first':'';
$class_first .= (($k-1)%(int)$options->devices_mobileportrait == 0)?' mobileportrait-first':'';
?>

<?php
$now = date("Y-m-d");
$newsFrom= substr($_product->getData('news_from_date'),0,10);
$newsTo=  substr($_product->getData('news_to_date'),0,10);
$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
$class = '';
if($now>=$newsFrom && $now<=$newsTo) $class .= ' have-iconew';
if($specialprice) $class .= ' have-icosale';
$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();

?>
	<div class="item item-animate<?php echo $class_first; ?>">
		<div class="item-inner clearfix<?php echo $class; ?>">
    		<div class="badges">
                <?php
                if ($now>=$newsFrom && $now<=$newsTo)
                    echo "<span class='ico-product ico-new'>New</span>";
                if (isset($price) && isset($finalPrice) && $finalPrice < $price && $themeConfig['general_useTagNew']==1)
                    echo "<span class='ico-product ico-sale'>-".floor(100-($finalPrice/$price)*100)." %</span>";
                ?>
            </div>
            <div class="item-img">
            	
                <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                	<span class="image-main">
                    	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($options->item_image_width, $options->item_image_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                	</span>
                </a>
                <?php  if(class_exists('Sns_Quickview_Helper_Data') && Mage::getStoreConfigFlag('quickview/general/enable') == 1){ ?>
                    <div class="quickview-wrap">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" style="display:none"></a>
                    </div>
                <?php } ?>
            </div>

            <div class="item-info">
                <div class="info-inner">	
                    <?php if( $options->item_title_display == 1 ) : ?>
                    <div class="item-title">
                        <a href="<?php echo $item->link ?>" onclick="javascript: return true"  title="<?php echo $item->title?>" >
						<?php echo $item->title; ?>
						</a>
                    </div>
                    <?php endif; ?>
                    <?php if( $options->item_desc_display == 1 ){?>
                    <div class="item-des">
                        <?php echo $item->description; ?>
                    </div>
                    <?php }
                    if( $options->item_price_disp == 1 ){ ?>
                    <div class="item-price">
                        <?php echo $this->getPriceHtml($_product, false, $uniqued) ?>
                    </div>
                    <?php }?>
                    <?php
                    if( $options->item_review_disp == 1 ){ ?>
                    <div class="rating">
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                    </div>
                    <?php } ?>
                    <div class="actions">
                        <?php if( $options->item_cart_disp == 1 ) {?>
                        <?php if($_product->isSaleable()): ?>
                            <button title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Cart') ?>"><?php //echo $this->__('Add to Cart') ?></button>
                        <?php else: ?>
                            <span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
                        <?php endif; ?>
                        <?php } ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow() && $options->item_wishlist_disp == 1 ): ?>
                                <li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Wishlist') ?>"><?php //echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($this->helper('catalog/product_compare')->getAddUrl($_product) && $options->item_compare_disp == 1): ?>
                                <li><a title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $this->helper('catalog/product_compare')->getAddUrl($_product) ?>" class="link-compare" data-toggle="tooltip" data-original-title="<?php echo $this->__('Add to Compare') ?>"><?php //echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>

                </div>
            </div>
		</div>

	</div>
<?php }
}?>

<?php 
$classloaded = ($options->number_per_display >= $total || $options->number_per_display == 0 )?' loaded':'';
?>

<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($){
    pdtlm = $('.inner-<?php echo $uqtab ?>').parents('.pdt-content').find('.pdt-loadmore');
    if(!pdtlm.hasClass('data-inserted')){
        pdtlm.addClass('data-inserted');
        pdtlm.attr('data-all', '<?php echo $total;?>');
        pdtlm.find('.btn-loadmore').addClass("<?php echo $classloaded?>");
        <?php if($classloaded): ?>
            pdtlm.find('.loadmore').attr('data-label', '<?php echo $this->__("All ready"); ?>');
            pdtlm.find('.loadmore').attr('data-label-load', '<?php echo $this->__("All ready"); ?>');
        <?php else: ?>
            pdtlm.find('.loadmore').attr('data-label', '<?php echo $this->__("View more item"); ?>');
            pdtlm.find('.loadmore').attr('data-label-load', '<?php echo $this->__("Loading ..."); ?>');
        <?php endif; ?>
        <?php if($options->show_number_loadmore): ?>
            pdtlm.find('.load-number').attr('data-more', '<?php echo ( $total - $options->number_per_display <= $options->number_per_display )?($total - $options->number_per_display):$options->number_per_display ?>');
            pdtlm.find('.data-total').attr('data-total', '<?php echo ($total - $options->number_per_display) ?>');
        <?php endif; ?>
        <?php if( $total > $options->number_per_display ): ?>
            pdtlm.find('.load-number').html("/");
        <?php endif; ?>
    }
 });
//]]>
</script>
</div>
