<?php
/*------------------------------------------------------------------------
 # SNS RevolutionSlider - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$config = $this->getConfigObject();
$uq = rand().time();
?>

<div class="sns-revolutionslider-wrap">
	<?php if($config['layout']) echo '<div class="container">'; ?>
		<div class="wrap-inner">
			<?php 
			$slides = explode(',', $config['slides_html']);
			if(count($slides) > 0){
			?>
		    <div class="sns-revolutionslider" id="sns_revolutionslider<?php echo $uq ?>">
				<ul>
		    	<?php 
		    	for($i=0;$i<count($slides);$i++) {
		    		echo str_replace('</ul>', '', str_replace('<ul>', '', $this->getLayout()->createBlock('cms/block')->setBlockId(trim($slides[$i]))->toHtml()));
		    	}?>
				</ul>
				<div class="tp-bannertimer<?php echo ($config['timerbar']=='bottom')?' tp-bottom':'';?>"></div>
		    </div>
		    <?php } ?>
		</div>
	<?php if($config['layout']) echo '</div>'; ?>
	<script type="text/javascript">
		// <![CDATA[
			jQuery(document).ready(function($) {
			  $('#sns_revolutionslider<?php echo $uq ?>').revolution({
				delay:<?php echo ($config['delay']); ?>,
				startwidth: 1140,
				startheight: 450,
		 		onHoverStop: "off",
		 		navigationArrows:"<?php echo ($config['navigationArrows']); ?>", // nextto, solo, none

				navigationType:"<?php echo ($config['navigationType']); ?>", // bullet, thumb, none
				navigationStyle:"<?php echo ($config['navigationStyle']); ?>", // round,square,navbar,round-old,square-old,navbar-old
				 	 
				navigationHAlign:"center",
				navigationVAlign:"bottom",
				navigationVOffset:10,	
				 	 
		 		<?php if(!$config['autoplay']){?>
		 		stopAtSlide:1,
		 		stopAfterLoops:0,
		 		<?php } ?>			 
		 
				 fullScreenOffsetContainer:"#sns_header, #sns_menu"
			  });
		   });
		// ]]>
	</script>
</div>
    	
    	
    	
    	
    	
    	