<?php $posts = $this->getPosts(); ?>
<?php
	if($posts) :
	$blockId ='sns_latestblog_'.rand().time();
?>
<div class="block block-latestblog" id="<?php echo $blockId; ?>">
	<div class="block-title">
		<strong><?php echo $this->__('Latest Blog');?></strong>
	</div>
	<div class="block-content">
		<div class="navslider">
			<a class="prev" href="#"><i class="fa fa-angle-left"></i></a>
			<a class="next" href="#"><i class="fa fa-angle-right"></i></a>
		</div>
	    <div class="list-blog">
	    <?php $j=0; foreach ($posts as $post): ?>
	        <?php
		        $j++;
		        if($j>8) break;
			?>
	        <div class="item-post<?php echo ($i==4)?' last':'';?> clearfix">
	            <?php
		            $str = $post->getPostContent();
		            $str = preg_replace ( "/\<img[^\>]*>/", '', $post->getPostContent());
	            ?>
	            <a class="post-img banner" href="<?php echo $post->getAddress(); ?>" >
	                <?php echo Mage::helper('toronto/data')->getImgHtml($post->getPostContent(), 265, 145); ?>
	            </a>
	            	
	            <div class="post-title">
	                <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
	            </div>
	            <div class="date">
	                <?php
	                $_ct= new Zend_Date($post->getCreatedTime()); ?>
	                <i class="icon_table"></i>
	                <?php echo $_ct->toString('MMM').' '.$_ct->toString('d').', '.$_ct->toString('YYY');  ?>
	            </div>
	            <div class="post-content">
	                <?php echo Mage::helper('core/string')->truncate($str, 80); ?>
	                <!--<br />
	                <a href="<?php echo $post->getAddress(); ?>" class="readmore"><?php echo $this->__('Read more'); ?></a> -->
	            </div>
	        </div>
	    <?php endforeach; ?>
	    </div>
	</div>
	<script>
		jQuery(document).ready(function($) {
			$(window).load(function(){
				$('#<?php echo $blockId; ?> .list-blog').owlCarousel({
					items: 1,
					itemsCustom: [
						[0, 1],[640, 2],[768, 3],[992, 4],[1170, 4] 
					],
					pagination: false,
					itemsScaleUp : true,
					slideSpeed : 800,
					autoPlay: false,
					addClassActive: true,
					afterAction: function (e) {
					    if(this.$owlItems.length > this.options.items){
					        $('#<?php echo $blockId; ?> .navslider').show();
					    }else{
					        $('#<?php echo $blockId; ?> .navslider').hide();
					    }
					}
				});
				$('#<?php echo $blockId; ?> .navslider .prev').on('click', function(e){
					e.preventDefault();
					$('#<?php echo $blockId; ?> .list-blog').trigger('owl.prev');
				});
				$('#<?php echo $blockId; ?> .navslider .next').on('click', function(e){
					e.preventDefault();
					$('#<?php echo $blockId; ?> .list-blog').trigger('owl.next');
				});
			});
		});
	</script>
</div>
<?php endif; ?>